spring:
  cloud:
    gateway:
      routes:
        - id: bing-route
          uri: https://cn.bing.com/
          predicates:
            - name: Path
              args:
                patterns: /search
            - name: Query
              args:
                param: q
                regexp: haha
            - name: Vip
              args:
                param: user
                value: yuanbao
          order: 10
          metadata:
            hello: world
        - id: order-route
          uri: lb://service-order
#         断言
          predicates:
            - name: Path
              args:
                patterns: /api/order/**
                matchTrailingSlash: true
        - id: product-route
          uri: lb://service-product  # lb意思是负载均衡，需要先引入loadbalancer模块
          predicates:
            - Path=/api/product/**


